linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - lll
    - gochecknoinits
    - gochecknoglobals

issues:
  exclude-use-default: false
